//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CompanyName.UI.Assets
{
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources()
        {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CompanyName.UI.Assets.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Abort.
        /// </summary>
        public static string Abort
        {
            get
            {
                return ResourceManager.GetString("Abort", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Application will be closed.
        /// </summary>
        public static string ApplicationClosed
        {
            get
            {
                return ResourceManager.GetString("ApplicationClosed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Automation.
        /// </summary>
        public static string Automation
        {
            get
            {
                return ResourceManager.GetString("Automation", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Close application?.
        /// </summary>
        public static string CloseQuestion
        {
            get
            {
                return ResourceManager.GetString("CloseQuestion", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string Confirm
        {
            get
            {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Devices.
        /// </summary>
        public static string Devices
        {
            get
            {
                return ResourceManager.GetString("Devices", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Failed.
        /// </summary>
        public static string Failed
        {
            get
            {
                return ResourceManager.GetString("Failed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Initialisation.
        /// </summary>
        public static string Init
        {
            get
            {
                return ResourceManager.GetString("Init", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Loading.
        /// </summary>
        public static string Loading
        {
            get
            {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Login denied.
        /// </summary>
        public static string LoginDenied
        {
            get
            {
                return ResourceManager.GetString("LoginDenied", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Please authenticate.
        /// </summary>
        public static string LoginPrompt
        {
            get
            {
                return ResourceManager.GetString("LoginPrompt", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Messages.
        /// </summary>
        public static string Messages
        {
            get
            {
                return ResourceManager.GetString("Messages", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No
        {
            get
            {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string Ok
        {
            get
            {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password
        {
            get
            {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string Reset
        {
            get
            {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to System.
        /// </summary>
        public static string System
        {
            get
            {
                return ResourceManager.GetString("System", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string Username
        {
            get
            {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes
        {
            get
            {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
